apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress-host
spec:
  rules:
  - host: "*.podinfo.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: podinfo
            port:
              number: 9898
